openapi: 3.0.3
info:
  title: Books API
  description: API for managing personal book collection
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /api/books:
    get:
      tags:
        - books
      summary: Get all books
      operationId: getBooks
      responses:
        '200':
          description: List of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'

components:
  schemas:
    Book:
      type: object
      required:
        - id
        - title
        - author
        - publicationYear
        - readYear
        - language
        - format
        - finishDate
      properties:
        id:
          type: integer
          format: int64
          example: 1
        title:
          type: string
          example: "The Great Gatsby"
        author:
          type: string
          example: "F. Scott Fitzgerald"
        publicationYear:
          type: integer
          example: 1925
        readYear:
          type: integer
          example: 2023
        language:
          type: string
          example: "English"
        format:
          type: string
          enum: [PAPERBACK, EBOOK]
          example: "PAPERBACK"
        finishDate:
          type: string
          format: date
          example: "2020-01-15"
        readingTimeInDays:
          type: integer
          example: 14